### ISSUE TITLE
Missing frame id and stamp in msgs

### ISSUE THREAD

**Issue by astumpf** [ethz-asl/wavemap#26]
The latest changes introduced a minor error. When using non-hashed octree the map msg is missing header information.
The code [here ](https://github.com/ethz-asl/wavemap/blob/10a82192f553b7251b4ee7190d92c4da90fad943/ros/wavemap_ros/src/wavemap_server.cc#L78) should be

```
      if (convert::mapToRosMsg(*occupancy_map_, config_.world_frame,
                              ros::Time::now(), map_msg)) {
```

**Comment by victorreijgwart** [comment]
Hi Alexander,
Thanks for spotting this! The suggested fix looks good. Shall I open a PR for it, or would you like to do it?

**Comment by astumpf** [comment]
Opened a pr: https://github.com/ethz-asl/wavemap/pull/27

**Comment by victorreijgwart** [comment]
Thanks!
