### ISSUE TITLE
RViz plugin does not render in topdownortho correctly

### ISSUE THREAD

**Issue by astumpf** [ethz-asl/wavemap#51]
**Describe the bug**
RViz plugin does not render min cell size in topdownortho view.

**To Reproduce**
Set RViz camera view to `topdownortho`

**Expected behavior**
The octree should be rendered in min cell size.

**Observed outcome**
The octree is not rendered in min cell size.

**Screenshots**
Rendering min cell size:
![Screenshot from 2023-12-12 13-00-12](https://github.com/ethz-asl/wavemap/assets/7815721/68bbda51-2bca-4c19-9c7e-f5442c854f73)
Not rendering min cell size:
![Screenshot from 2023-12-12 13-07-38](https://github.com/ethz-asl/wavemap/assets/7815721/15d58df6-c9fe-43b5-a4eb-55b743a0d4dd)

**System information (please complete if relevant):**
 - OS: Ubuntu 18.04
 - Wavemap
   - install: native
   - version: v1.5.2

**Runtime information (please complete if relevant):**

**Additional context**

**Comment by victorreijgwart** [comment]
Hey!
The bug is reproducible. It seems to be related to the LoD rendering we use to get Rviz to run at a reasonable frame rate. This depends on the camera position, which apparently glitches in `topdownortho` mode.
I'll push a fix later today.

**Comment by victorreijgwart** [comment]
You can now try the fix by cherry-picking commit [b6e1336](https://github.com/ethz-asl/wavemap/commit/b6e1336f094af4155bde4827953f5c83702cdca2) or checking out the [feature/plugin_system](https://github.com/ethz-asl/wavemap/tree/feature/plugin_system) branch.

**Comment by astumpf** [comment]
Can verify, that this fix solves the issue. Thank you!

**Comment by victorreijgwart** [comment]
Great. Thanks for letting me know!
