### ISSUE TITLE
The size of Map message is too big

### ISSUE THREAD

**Issue by gyeongmin6099** [ethz-asl/wavemap#55]
**Question**
Thank you for your marvelous work. 
I'm trying to run `wavemap` in the small area with `min_cell_width : 0.05`.
If `min_cell_width : 0.1`, the size of Map message isn't too big, but it has 10 times bigger size about a few MB with `min_cell_width:0.05`. And It's too big to send from device to ubuntu machine in real time.
 **Is there way to reduce the size of Map message?**
Thanks.

**Runtime information:**

- Launch file: [Custom]
- Config file: [hasehd_chunked_wavelet_octree, hashed_chunked_wavelet_integrator, continuous_beam]
- Custom setup:                                        # For online use or personal datasets
    - depth sensor: [TOF]
    - pose source: [Odometry from PX4]

**System information:**

- CPU: [QRB5165]
- RAM: [8GB]
- OS: [e.g. Ubuntu 18.04]
- Wavemap
    - install: [Native]
    - version: [v1.4.0]

**Comment by victorreijgwart** [comment]
Hi @gyeongmin6099, thanks for trying out wavemap!

One setting that might help is the [`map/general/max_num_blocks_per_msg`](https://ethz-asl.github.io/wavemap/pages/configuration/map.html#:~:text=max_num_blocks_per_msg). Wavemap transmits the map updates incrementally. If you set `max_num_blocks_per_msg` to a lower value, it will also split the updates into multiple smaller messages. Note that this will decrease the message size, but the bandwidth will stay the same.

Depending on your use case, there're probably additional things you can configure. When you say the messages are too big, is the issue packet-loss (e.g. unreliable WiFi), is there a hard limit on the max message size (e.g. hardware limits on the embedded device), or are you having issues with limited bandwidth (e.g. slow WiFi or a radio)? How do you intend to use the maps on the ubuntu machine? Does it run Rviz, a planner, or something else?

**Comment by gyeongmin6099** [comment]
Thank you for your fast response :)
I could fix my problem by changing `max_num_blocks_per_msg` and There was a issure from my radio!
Now I'm trying to render the 3D Map data on Rviz, But I want to change some code later so that I can render the map on web viewer or something.
Thanks for your help:) Lemme close this issue

**Comment by gyeongmin6099** [comment]
Hi @victorreijgwart I have one more question!
Is there a way to colorize wavemap with RGB input?
If so, Do you have a plan to add the feature?
Thanks a lot!

**Comment by victorreijgwart** [comment]
Hi @gyeongmin6099, great to hear that changing `max_num_blocks_per_msg` solved your issue!

Yes, it would be possible to add colors to the map. The main changes that would be needed would be to add a map data structure that includes a color channel (alongside the occupancy) and a compatible measurement integrator.
Unfortunately, I personally won't have time to work on this in the next few months though. Would you be interested in working on this?

Let me know how it goes with rendering the maps in a browser. That'd be a really awesome feature!

**Comment by gyeongmin6099** [comment]
I'm interested in it! If this project can make 3D Map like the real world. It would be awesome!

**Comment by victorreijgwart** [comment]
@gyeongmin6099, that's great! Let's continue the discussion on how to get started with this feature in [this issue](https://github.com/ethz-asl/wavemap/issues/56) as it has a matching title. Then others can easily find it and join.
