### ISSUE TITLE
Are there any plans to add a function to integrate color information?

### ISSUE THREAD

**Issue by Tacha-S** [ethz-asl/wavemap#56]
**Question**
Are there any plans to add a feature that integrates the color information from color images into volumetric mapping, similar to the existing feature that integrates depth images into volumetric mapping?

**Comment by victorreijgwart** [comment]
Hi @Tacha-S,
The main upcoming features are a [plugin system](https://github.com/ethz-asl/wavemap/tree/feature/plugin_system) (to make it easy to extend wavemap with functionalities like [local mapping](https://github.com/ethz-asl/wavemap/issues/25#issuecomment-1820670145)) and large set of tooling for path planning (ESDFs, global planners, etc). Unfortunately, I won't have time to work on integrating color information myself in the coming months as I'm quite busy finishing my PhD. Would you be interested in working on it? If so, you could collaborate with [gyeongmin6099](https://github.com/gyeongmin6099) who mentioned he would also be interested in working on this (see [this issue](https://github.com/ethz-asl/wavemap/issues/55)).

**Comment by victorreijgwart** [comment]
I created a matching feature request [here](https://github.com/ethz-asl/wavemap/issues/57), in case you're interested in contributing or joining the discussion.

**Comment by Tacha-S** [comment]
Thank you for the information.
I apologize for not finding #55 , even though you were having a similar discussion.
When I have time, I plan to contribute to the discussion and PRs.

Since there is already an issue created for the discussion, I will close this issue.
