### ISSUE TITLE
How to generate a 2d costmap or occupancy grid efficiently?

### ISSUE THREAD

**Issue by YoungCapta1n** [ethz-asl/wavemap#65]
Thanks for providing the great volumetric mapping tool. I am interested in mapping and path planning of autonomous surface vehicles(ASV), which requires 2d costmap in most instances. When the vehicle travels under a bridge, it is necessary to perform an efficient volumetric mapping for safe navigation. if you could provide me with some hints about the 2d costmap generation from volumetric mapping results I would really appreciate it!

**Comment by victorreijgwart** [comment]
Hi @YoungCapta1n,

In general, I agree with you that using 3D maps is useful even for robots that only move in 2D. Aside from naturally handling overhanging objects like bridges, it also generally results in a cleaner map. Flattening the world, which is inherently 3D, into a 2D representation leads to a lot of contradictory observations (think of a small table whose top will be hit by some beams while many others pass under/over it), which in turn generates a lot of noise.

Extracting a 2D cost map from wavemap should be straightforward, and in past projects we did it in two steps. The first is to identify the driveable base surface (e.g. as a plane or even a mesh). The second is to project a slice of the 3D map onto this surface to classify which parts of the surface the robot can stand on without colliding with overhanging obstacles.

How do you currently characterize the 2D surface you intend to drive on? Is it just a horizontal 2D plane? If so, is it at a constant height (z-coordinate) or does it vary? Alternatively, you can also run some ground plane extraction or even extract a mesh from the map to characterize the drivable surface.

Once you have the surface, classifying the parts that the robot can stand on without being in collision is straightforward. You can simply iterate over the surface in 2D (x, y) and check that all the voxels that are closer to the surface than the robot's height are free (i.e. `Occupancy::is_free(x,y,z) for all z in [z_surface, z_surface+h_robot]`).

**Comment by YoungCapta1n** [comment]
Thanks for your time! I will use this awesome mapping library in my robot.

**Comment by victorreijgwart** [comment]
Glad to hear that @YoungCapta1n!
