### ISSUE TITLE
compile error using wavemap 2.0 with LIVOX_AVAILABLE

### ISSUE THREAD

**Issue by YoungCapta1n** [ethz-asl/wavemap#67]
**Question**
Thanks for updating wavemap. I've tested wavemap 1.6.3 with livox mid360, it works very well. 
When I try a native installation with wavemap 2.0, it cannot build successfully. The compile error is shown as follows,

**Images**
![Screenshot from 2024-08-29 17-32-34](https://github.com/user-attachments/assets/183591ff-e8a5-409b-846e-b1f5181fcc7f)

- CPU: [Intel i9-9900K]
- GPU: [Nvidia RTX 2080Ti]  # Only for visualization-related issues
- RAM: [32GB]
- OS: [Ubuntu 20.04]
- Wavemap
    - install: [Native (ROS noetic with catkin); ]
    - version: [e.g., v2.0.0]

**Comment by YoungCapta1n** [comment]
> Thanks a lot for reporting this @YoungCapta1n. Something must have gone wrong when refactoring, and it slipped through our tests. I'll dig into it and get back to you this afternoon.

I try to modify the code as follows, All 7 packages succeeded! 

src/wavemap/interfaces/ros1/wavemap_ros/include/wavemap_ros/inputs/impl/pointcloud_topic_input_impl.h
![Screenshot from 2024-08-29 18-08-09](https://github.com/user-attachments/assets/f6489a56-5521-4d31-ba2c-548fa1521a6d)

src/wavemap/interfaces/ros1/wavemap_ros/src/inputs/pointcloud_topic_input.cc
![image](https://github.com/user-attachments/assets/aaae08ef-59ea-4dab-afbd-2d358f2b838b)

**Comment by YoungCapta1n** [comment]
I have another issue when using wavemap 2.0. 
The crop operation has been added to the config file.
![image](https://github.com/user-attachments/assets/d0e22798-54ed-4c2b-8199-ae997eb26bb1)

It gives an error when using lookupTransform() function.
![image](https://github.com/user-attachments/assets/54343e11-5026-4397-885c-77fc9ff999eb)

**Comment by YoungCapta1n** [comment]
> body_frame

Thanks for your reply!.  `body_frame: "livox_frame"` gives the same warning. I've tried the crop operation on wavemap branch `feature/plugin_system`, it works well!

**Comment by victorreijgwart** [comment]
@YoungCapta1n, I added you as a co-author for this fix to acknowledge your contribution (see #68). But I wanted to check with you just in case. If you would prefer not to be mentioned, let me know - the commit can still be changed before it gets merged.

**Comment by victorreijgwart** [comment]
One thing that changed between the `feature/plugin_system` branch and release `v2.0.0` is that the TF lookup happens based on the timestamp of `ros::Time::now()` instead of using the timestamp of the last measurement. We had to make this change to support ROS-agnostic operations in wavemap's C++ library.

In your tests, are you replaying a rosbag? If so, could you check if you set `/use_sim_time: true` and run rosbag play with the `--clock` argument?

**Comment by YoungCapta1n** [comment]
> One thing that changed between the `feature/plugin_system` branch and release `v2.0.0` is that the TF lookup now happens based on the timestamp of `ros::Time::now()` instead of using the timestamp of the last measurement. We had to make this change to support ROS-agnostic map operations in wavemap's C++ library.
> 
> In your tests, are you replaying a rosbag? If so, could you check if you set `/use_sim_time: true` and run rosbag play with the `--clock` argument?

Thanks for your reply. I use wavemap2.0 with real-time stream of MID-360, not rosbag. I will check the timestamp and test the crop operation.

**Comment by victorreijgwart** [comment]
Hi @YoungCapta1n, I'll close this issue for now since the bug is fixed. If you have follow-up questions or would like to discuss how the timing is handled for map operations, don't hesitate to open a new issue :)
